import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import type { StorageProvider } from "./provider.js";

function assertSafeKey(key: string): string {
  if (!key || key.includes("..") || path.isAbsolute(key) || key.includes("\\") || key.includes("\0")) {
    throw new Error("unsafe storage key");
  }
  return key;
}

/**
 * Local filesystem storage. Keys are generated by the media service
 * (`sites/<siteId>/<uuid>.<ext>`) and are validated here defensively against
 * path traversal. This is the reference implementation of StorageProvider;
 * R2/S3-compatible backends implement the same contract.
 */
export class LocalStorageProvider implements StorageProvider {
  readonly name = "local";

  constructor(private readonly root: string) {}

  private resolve(key: string): string {
    return path.join(this.root, assertSafeKey(key));
  }

  async put(input: { key: string; data: Buffer; mimeType: string }): Promise<void> {
    const target = this.resolve(input.key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, input.data);
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.resolve(key));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    await unlink(this.resolve(key)).catch(() => {});
  }
}
